// psp-js 3DS host: boots QuickJS, exposes the same gfx/log/frame(buttons) API
// the PSP and Web builds provide, and runs the exact same game .js file.
//
// The game's 480x272 logical screen is uniform-scaled to fit the 3DS top
// screen (400x240) and vertically centered. Logs go to the bottom screen.
#include <3ds.h>
#include <citro2d.h>
#include <citro3d.h>
#include <stdio.h>
#include <string.h>

#include "quickjs.h"
#include "game_js.h"   // generated: GAME_JS[] and GAME_JS_LEN
#include "vshader_shbin.h" // generated by picasso from source/vshader.v.pica

#define LOGIC_W 480.0f
#define LOGIC_H 272.0f

// ── 3D wire constants (the cross-host g3d contract; see framework/src/g3d.ts).
// These MUST match the JS/Rust copies byte-for-byte; framework/test/contract.ts
// greps these exact names+values and asserts parity. Keep `#define NAME 0x...`.
#define DC3D_MAGIC     0x44433344   // 'DC3D' little-endian
#define DC3D_VERSION   0x0002

#define OP_SET_CAMERA  0x0001
#define OP_DRAW        0x0002
#define OP_IMM_TRIS    0x0003
#define OP_BIND_TEXTURE 0x0004      // v2: declared for wire-parity; citro3d impl additive (TODO)
#define OP_SET_LIGHTS  0x0005
#define OP_DRAW_SKINNED 0x0006
#define OP_SET_FOG     0x0007

#define FMT_POS        0x0001       // 3 x f32
#define FMT_COLOR      0x0002       // u32 ABGR
#define FMT_NORMAL     0x0004       // 3 x f32
#define FMT_UV         0x0008       // 2 x f32
#define FMT_WEIGHTS    0x0010       // bone weights (count per-mesh)

// v1 vertex = u32 ABGR color + 3 f32 position, interleaved, 16-byte stride.
#define V1_STRIDE      16

// The 3D pass clears the color buffer to this (matches the reference rasterizer
// framework/test/raster3d.ts: BG = RGB(0x10,0x14,0x1e)).
#define BG_R 0x10
#define BG_G 0x14
#define BG_B 0x1e

static C3D_RenderTarget *g_top;
static float g_scale, g_offy;

// ── Retained-mesh storage. uploadMesh COPIES the JS bytes into persistent
// linearAlloc buffers (the GPU DMAs from linear, cache-coherent memory; a raw
// JS_GetArrayBuffer pointer renders garbage on hardware). Handles are indices.
#define MAX_MESHES 256
typedef struct {
    void *verts;     // linearAlloc'd interleaved vertex bytes (V1_STRIDE each)
    void *indices;   // linearAlloc'd u16 indices, or NULL for non-indexed
    int   vcount;    // number of vertices
    int   icount;    // number of indices (0 -> draw sequential vcount)
    int   format;    // vertex format bitfield (v1 = FMT_POS|FMT_COLOR)
    int   used;
} Mesh3D;
static Mesh3D g_meshes[MAX_MESHES];

// ── 3D pipeline state (set up once in sceneInit).
static DVLB_s        *g_vshader_dvlb;
static shaderProgram_s g_program;
static int            g_uLoc_mvp;   // "mvp" uniform location
static C3D_AttrInfo   g_attr;       // attr0 = pos f32x3, attr1 = color u8x4
static C3D_Mtx        g_viewProj;   // tilt * (latest SET_CAMERA), ready for mvp
// The 3DS top screen is scanned rotated 90°. citro3d's Mtx_PerspTilt bakes that
// into the projection, but our projection comes from shared JS without it, so we
// left-multiply every camera matrix by this constant 90° screen-space rotation.
static C3D_Mtx        g_tilt;

// Scratch VBO for OP_IMM_TRIS — double-buffered linearAlloc to avoid GPU/CPU
// races under C3D_FRAME_SYNCDRAW.
#define IMM_VBO_BYTES (64 * 1024)
static void *g_immVbo[2];
static int   g_immFrame;

// QuickJS (this fork) calls debug_log() unconditionally during init; provide it.
void debug_log(const char *msg, int a) { (void)a; printf("[qjs] %s\n", msg); }

static inline u32 col(int r, int g, int b) {
    return C2D_Color32((u8)(r & 255), (u8)(g & 255), (u8)(b & 255), 0xFF);
}

// gfx.clear(r,g,b) — fill the screen with a color (the cross-host contract:
// clear does nothing but paint the background). Scene setup is the host loop's
// job: C2D_SceneBegin(g_top) is called once per frame in main() before frame()
// runs, and the render target never changes, so clear must NOT re-begin it.
static JSValue js_gfx_clear(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    int32_t r = 0, g = 0, b = 0;
    if (argc >= 3) {
        JS_ToInt32(ctx, &r, argv[0]);
        JS_ToInt32(ctx, &g, argv[1]);
        JS_ToInt32(ctx, &b, argv[2]);
    }
    C2D_TargetClear(g_top, col(r, g, b));
    return JS_UNDEFINED;
}

// gfx.fillRect(x,y,w,h,r,g,b)
static JSValue js_gfx_fillRect(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc < 7) return JS_UNDEFINED;
    int x, y, w, h, r, g, b;
    JS_ToInt32(ctx, &x, argv[0]);
    JS_ToInt32(ctx, &y, argv[1]);
    JS_ToInt32(ctx, &w, argv[2]);
    JS_ToInt32(ctx, &h, argv[3]);
    JS_ToInt32(ctx, &r, argv[4]);
    JS_ToInt32(ctx, &g, argv[5]);
    JS_ToInt32(ctx, &b, argv[6]);

    // Clip to the logical screen before scaling, so out-of-range coords behave
    // like the Web canvas and the golden render mock (both clamp to the screen).
    int x0 = x < 0 ? 0 : x, y0 = y < 0 ? 0 : y;
    int x1 = x + w, y1 = y + h;
    if (x1 > (int)LOGIC_W) x1 = (int)LOGIC_W;
    if (y1 > (int)LOGIC_H) y1 = (int)LOGIC_H;
    if (x1 <= x0 || y1 <= y0) return JS_UNDEFINED; // fully off-screen / empty

    C2D_DrawRectSolid(x0 * g_scale, y0 * g_scale + g_offy, 0.0f,
                      (x1 - x0) * g_scale, (y1 - y0) * g_scale, col(r, g, b));
    return JS_UNDEFINED;
}

// log(msg) -> bottom-screen console
static JSValue js_log(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc >= 1) {
        const char *s = JS_ToCString(ctx, argv[0]);
        if (s) { printf("%s\n", s); JS_FreeCString(ctx, s); }
    }
    return JS_UNDEFINED;
}

// ── 3D pipeline setup. Parses the picasso-compiled vertex shader, builds the
// shader program, caches the MVP uniform location, and declares the vertex
// layout. (TexEnv is (re)set per-submit because C2D_Prepare clobbers it.)
// Called once from main() after C3D/C2D are up.
static void sceneInit(void) {
    g_vshader_dvlb = DVLB_ParseFile((u32 *)vshader_shbin, vshader_shbin_size);
    shaderProgramInit(&g_program);
    shaderProgramSetVsh(&g_program, &g_vshader_dvlb->DVLE[0]);

    g_uLoc_mvp = shaderInstanceGetUniformLocation(g_program.vertexShader, "mvp");

    // Vertex layout: attr0 = position (3 f32), attr1 = color (4 u8 = ABGR).
    // The GPU normalizes the u8 color to [0,1]; the byte order on the wire is
    // R,G,B,A (the u32 ABGR is little-endian, so byte0=R..byte3=A), which is the
    // order GPU_UNSIGNED_BYTE x4 feeds into color0.x=R..color0.w=A.
    AttrInfo_Init(&g_attr);
    AttrInfo_AddLoader(&g_attr, 0, GPU_FLOAT, 3);          // v0 = position
    AttrInfo_AddLoader(&g_attr, 1, GPU_UNSIGNED_BYTE, 4);  // v1 = color (ABGR)

    g_immVbo[0] = linearAlloc(IMM_VBO_BYTES);
    g_immVbo[1] = linearAlloc(IMM_VBO_BYTES);

    Mtx_Identity(&g_viewProj);
    // 90° screen-space rotation for the rotated top screen (see g_tilt decl).
    Mtx_Identity(&g_tilt);
    Mtx_RotateZ(&g_tilt, 1.57079632679f, true); // +90 degrees
}

// Load a column-major wire matrix (m[col*4+row], 16 f32) into a C3D_Mtx.
// citro3d's vertex shader dot-products mtx.r[i] (a ROW) with the position, so a
// C3D_Mtx holds the matrix row-major: r[row] = (m row). We therefore TRANSPOSE
// the column-major wire bytes here (verified on hardware). Using .r[i].x/.y/.z/.w
// (not the .m[] union) avoids citro3d's reversed C3D_FVec component packing.
static void wireToMtx(C3D_Mtx *out, const float *m) {
    for (int row = 0; row < 4; row++) {
        out->r[row].x = m[0 * 4 + row];
        out->r[row].y = m[1 * 4 + row];
        out->r[row].z = m[2 * 4 + row];
        out->r[row].w = m[3 * 4 + row];
    }
}

// g3d.uploadMesh(vertices, indices|null, format) -> int handle.
// COPIES the JS bytes into persistent linearAlloc buffers and returns a handle.
static JSValue js_g3d_uploadMesh(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc < 3) return JS_NewInt32(ctx, -1);
    int32_t format = 0;
    JS_ToInt32(ctx, &format, argv[2]);

    size_t vsize = 0, isize = 0;
    uint8_t *vptr = JS_GetArrayBuffer(ctx, &vsize, argv[0]);
    if (!vptr) return JS_NewInt32(ctx, -1);
    uint8_t *iptr = NULL;
    if (!JS_IsNull(argv[1]) && !JS_IsUndefined(argv[1]))
        iptr = JS_GetArrayBuffer(ctx, &isize, argv[1]);

    int h = -1;
    for (int i = 0; i < MAX_MESHES; i++) {
        if (!g_meshes[i].used) { h = i; break; }
    }
    if (h < 0) return JS_NewInt32(ctx, -1);

    Mesh3D *mesh = &g_meshes[h];
    mesh->verts = linearAlloc(vsize ? vsize : 1);
    memcpy(mesh->verts, vptr, vsize);     // copy NOW; never retain the GC pointer
    mesh->vcount = (int)(vsize / V1_STRIDE);

    if (iptr && isize) {
        mesh->indices = linearAlloc(isize);
        memcpy(mesh->indices, iptr, isize);
        mesh->icount = (int)(isize / sizeof(u16));
    } else {
        mesh->indices = NULL;
        mesh->icount = 0;
    }
    mesh->format = format;
    mesh->used = 1;
    return JS_NewInt32(ctx, h);
}

// g3d.freeMesh(handle) -> void.
static JSValue js_g3d_freeMesh(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc < 1) return JS_UNDEFINED;
    int32_t h = -1;
    JS_ToInt32(ctx, &h, argv[0]);
    if (h >= 0 && h < MAX_MESHES && g_meshes[h].used) {
        if (g_meshes[h].verts)   linearFree(g_meshes[h].verts);
        if (g_meshes[h].indices) linearFree(g_meshes[h].indices);
        g_meshes[h].verts = NULL;
        g_meshes[h].indices = NULL;
        g_meshes[h].used = 0;
    }
    return JS_UNDEFINED;
}

// Bind a mesh's vertex buffer and issue the draw (indexed or sequential).
static void drawMesh(Mesh3D *mesh) {
    C3D_BufInfo *bufInfo = C3D_GetBufInfo();
    BufInfo_Init(bufInfo);
    // Permutation 0x01: the buffer holds attr1 (color, 4B) THEN attr0 (pos, 12B),
    // matching the wire vertex layout [u32 color @0][3 f32 pos @4]. (0x10 would
    // read position from the color bytes -> garbage positions, nothing visible.)
    BufInfo_Add(bufInfo, mesh->verts, V1_STRIDE, 2, 0x01);
    if (mesh->icount > 0)
        C3D_DrawElements(GPU_TRIANGLES, mesh->icount, C3D_UNSIGNED_SHORT, mesh->indices);
    else
        C3D_DrawArrays(GPU_TRIANGLES, 0, mesh->vcount);
}

// g3d.submit(buffer, byteLength) -> void. THE per-frame 3D call. Runs FIRST in
// the frame; clears color+depth (reversed-Z), replays the draw list, then hands
// the GPU back to C2D so the gfx.fillRect HUD draws on top, depth off.
static JSValue js_g3d_submit(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc < 2) return JS_UNDEFINED;
    size_t bufSize = 0;
    uint8_t *base = JS_GetArrayBuffer(ctx, &bufSize, argv[0]);
    int32_t len = 0;
    JS_ToInt32(ctx, &len, argv[1]);
    if (!base || len < 8 || (size_t)len > bufSize) return JS_UNDEFINED;

    // Little-endian header: u32 magic, u16 version, u16 recordCount.
    u32 magic = base[0] | (base[1] << 8) | (base[2] << 16) | (base[3] << 24);
    if (magic != DC3D_MAGIC) return JS_UNDEFINED; // fail loudly on drift
    u16 recordCount = base[6] | (base[7] << 8);

    // ── Begin the 3D pass. Bind our program + vertex layout, enable reversed-Z
    // depth, and clear the top target to the shared background. NO back-face
    // culling — the reference rasterizer doesn't cull, so we mustn't either.
    C2D_Flush(); // flush any pending C2D batch before we steal the pipeline
    C3D_BindProgram(&g_program);
    C3D_SetAttrInfo(&g_attr);
    C3D_CullFace(GPU_CULL_NONE);
    // Pin the depthmap so depth = -z_ndc (z_ndc in the PICA's [-1,0]); paired with
    // the per-draw z-negate above, near -> depth 1, far -> 0.
    C3D_DepthMap(true, -1.0f, 0.0f);
    C3D_DepthTest(true, GPU_GEQUAL, GPU_WRITE_ALL); // keep nearer (higher depth)

    // TexEnv: output the interpolated vertex color directly (no texture). C2D
    // sets its own TexEnv each Prepare, so we (re)assert ours every 3D pass.
    C3D_TexEnv *env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, 0, 0);
    C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

    // Clear color to BG + depth to 0 (reversed-Z clears the far plane to 0).
    u32 clearColor = (BG_R << 24) | (BG_G << 16) | (BG_B << 8) | 0xFF; // RGBA8
    C3D_RenderTargetClear(g_top, C3D_CLEAR_ALL, clearColor, 0);
    C3D_FrameDrawOn(g_top);

    // bytes are 4-byte aligned per the wire (header 8B + 4B record headers), so
    // f32 reads are safe via memcpy into a local (avoid unaligned float loads).
    int o = 8;
    g_immFrame ^= 1; // alternate the scratch VBO per frame
    int immUsed = 0;
    for (int r = 0; r < recordCount && o + 4 <= len; r++) {
        u16 op = base[o] | (base[o + 1] << 8);
        u16 words = base[o + 2] | (base[o + 3] << 8);
        int payload = o + 4;
        o = payload + words * 4;
        if (o > len) break;

        if (op == OP_SET_CAMERA) {
            float m[16];
            memcpy(m, base + payload, 64);
            C3D_Mtx vp;
            wireToMtx(&vp, m);
            // Bake the 90° screen tilt in (left-multiply, so it rotates the final
            // projected image): g_viewProj = tilt * (proj*view).
            Mtx_Multiply(&g_viewProj, &g_tilt, &vp);
        } else if (op == OP_DRAW) {
            u32 handle = base[payload] | (base[payload + 1] << 8) |
                         (base[payload + 2] << 16) | (base[payload + 3] << 24);
            // (tint at payload+4 is ignored in v1: TexEnv = REPLACE primary color)
            float model[16];
            memcpy(model, base + payload + 8, 64);
            if (handle >= MAX_MESHES || !g_meshes[handle].used) continue;

            // mvp = viewProj * model (column vectors), uploaded as one uniform.
            C3D_Mtx modelMtx, mvp;
            wireToMtx(&modelMtx, model);
            Mtx_Multiply(&mvp, &g_viewProj, &modelMtx);
            // The PICA200 clips z to [-w, 0], but our shared reversed-Z projection
            // emits clip.z in [0, w] (near->w, far->0). NEGATE the z row to land in
            // the PICA range mapping near->-w (z_ndc -1), far->0 (z_ndc 0). With the
            // depthmap pinned to depth=-z_ndc (below), near->depth 1 / far->0, so the
            // GPU_GEQUAL + clear-0 test keeps the nearer fragment. Without this the
            // whole scene is z-clipped (clip.z>0) and nothing renders at all.
            mvp.r[2].x = -mvp.r[2].x;
            mvp.r[2].y = -mvp.r[2].y;
            mvp.r[2].z = -mvp.r[2].z;
            mvp.r[2].w = -mvp.r[2].w;
            C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, g_uLoc_mvp, &mvp);
            drawMesh(&g_meshes[handle]);
        } else if (op == OP_IMM_TRIS) {
            // Inline dynamic geometry (particles/tracers). Stage into the scratch
            // VBO, draw with the identity-model camera matrix (verts are in world
            // space — same as a DRAW with model = identity). Cap to the scratch.
            u32 vcount = base[payload] | (base[payload + 1] << 8) |
                         (base[payload + 2] << 16) | (base[payload + 3] << 24);
            int vbytes = (int)vcount * V1_STRIDE;
            const u8 *src = base + payload + 8;
            if (vbytes <= 0 || immUsed + vbytes > IMM_VBO_BYTES) continue;
            u8 *dst = (u8 *)g_immVbo[g_immFrame] + immUsed;
            memcpy(dst, src, vbytes);
            immUsed += vbytes;

            C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, g_uLoc_mvp, &g_viewProj);
            C3D_BufInfo *bufInfo = C3D_GetBufInfo();
            BufInfo_Init(bufInfo);
            BufInfo_Add(bufInfo, dst, V1_STRIDE, 2, 0x01); // color(4B) then pos(12B)
            C3D_DrawArrays(GPU_TRIANGLES, 0, (int)vcount);
        }
    }

    // ── End the 3D pass: hand the GPU back to citro2d for the HUD. C2D_Prepare
    // rebinds program+attr+buf, and we leave depth OFF so the subsequent
    // gfx.fillRect HUD (C2D_DrawRectSolid, z=0) draws on top in the same frame.
    C3D_DepthTest(false, GPU_GEQUAL, GPU_WRITE_ALL);
    C2D_Prepare();
    C2D_SceneBegin(g_top);
    return JS_UNDEFINED;
}

static void dump_exception(JSContext *ctx) {
    JSValue e = JS_GetException(ctx);
    const char *s = JS_ToCString(ctx, e);
    if (s) { printf("JS error: %s\n", s); JS_FreeCString(ctx, s); }
    JS_FreeValue(ctx, e);
}

int main(int argc, char **argv) {
    gfxInitDefault();
    consoleInit(GFX_BOTTOM, NULL);   // log output on the bottom screen
    C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);
    C2D_Init(C2D_DEFAULT_MAX_OBJECTS);
    C2D_Prepare();
    g_top = C2D_CreateScreenTarget(GFX_TOP, GFX_LEFT);
    sceneInit();   // build the custom 3D shader program + vertex layout

    // Uniform-scale the 480x272 logical screen to fit 400x240, centered.
    g_scale = 400.0f / LOGIC_W;                 // ~0.833
    g_offy = (240.0f - LOGIC_H * g_scale) / 2.0f;

    printf("psp-js (3DS) booting QuickJS...\n");
    printf("START+SELECT to quit.\n");

    JSRuntime *rt = JS_NewRuntime();
    JSContext *ctx = JS_NewContext(rt);
    JSValue global = JS_GetGlobalObject(ctx);

    JSValue gfx = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, gfx, "clear", JS_NewCFunction(ctx, js_gfx_clear, "clear", 3));
    JS_SetPropertyStr(ctx, gfx, "fillRect", JS_NewCFunction(ctx, js_gfx_fillRect, "fillRect", 7));
    JS_SetPropertyStr(ctx, global, "gfx", gfx);
    JS_SetPropertyStr(ctx, global, "log", JS_NewCFunction(ctx, js_log, "log", 1));

    // The optional 3D contract (framework/src/host3d.ts). A 2D-only game never
    // touches g3d; the framework probes `typeof g3d !== 'undefined'`.
    JSValue g3d = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, g3d, "uploadMesh", JS_NewCFunction(ctx, js_g3d_uploadMesh, "uploadMesh", 3));
    JS_SetPropertyStr(ctx, g3d, "freeMesh", JS_NewCFunction(ctx, js_g3d_freeMesh, "freeMesh", 1));
    JS_SetPropertyStr(ctx, g3d, "submit", JS_NewCFunction(ctx, js_g3d_submit, "submit", 2));
    JS_SetPropertyStr(ctx, global, "g3d", g3d);

    JSValue res = JS_Eval(ctx, (const char *)GAME_JS, GAME_JS_LEN, "game.js", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(res)) dump_exception(ctx);
    JS_FreeValue(ctx, res);

    JSValue frame = JS_GetPropertyStr(ctx, global, "frame");
    int have_frame = JS_IsFunction(ctx, frame);
    if (!have_frame) printf("WARN: game defined no global frame()\n");

    while (aptMainLoop()) {
        hidScanInput();
        u32 k = hidKeysHeld();
        if ((k & KEY_START) && (k & KEY_SELECT)) break;

        // Map 3DS keys to the canonical button bitmask (framework/src/input.ts Btn;
        // the // NAME tags are checked against it by framework/test/contract.ts).
        int mask = 0;
        if (k & KEY_UP)     mask |= 0x10;    // UP
        if (k & KEY_RIGHT)  mask |= 0x20;    // RIGHT
        if (k & KEY_DOWN)   mask |= 0x40;    // DOWN
        if (k & KEY_LEFT)   mask |= 0x80;    // LEFT
        if (k & KEY_A)      mask |= 0x4000;  // CROSS
        if (k & KEY_B)      mask |= 0x2000;  // CIRCLE
        if (k & KEY_X)      mask |= 0x8000;  // SQUARE
        if (k & KEY_Y)      mask |= 0x1000;  // TRIANGLE
        if (k & KEY_START)  mask |= 0x08;    // START
        if (k & KEY_SELECT) mask |= 0x01;    // SELECT

        C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
        C2D_SceneBegin(g_top);
        if (have_frame) {
            JSValue arg = JS_NewInt32(ctx, mask);
            JSValue ret = JS_Call(ctx, frame, global, 1, &arg);
            if (JS_IsException(ret)) dump_exception(ctx);
            JS_FreeValue(ctx, ret);
            JS_FreeValue(ctx, arg);
        }
        C3D_FrameEnd(0);
    }

    JS_FreeValue(ctx, frame);
    JS_FreeValue(ctx, global);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    C2D_Fini();
    C3D_Fini();
    gfxExit();
    return 0;
}
