// AUTO-GENERATED by bake/bake-sprites.ts from bake/sprite-defs.ts.
import { Bitmap, bitmapFromRows } from './bitmap';

export const SPRITES: Record<string, Bitmap> = {
  "hero": bitmapFromRows(["..hhhh..", ".hffffh.", ".fkffkf.", ".ffffff.", "..wkkw..", ".bbbbbb.", ".bb..bb.", ".bb..bb.", ".s....s.", ".s....s."], { "h": 0x3a2a18, "f": 0xe8c79a, "k": 0x202020, "w": 0xb05030, "b": 0x2f54c0, "s": 0x6a4a22 }),
  "villager": bitmapFromRows(["..hhhh..", ".hffffh.", ".fkffkf.", ".ffffff.", "..wkkw..", ".gggggg.", ".gg..gg.", ".gg..gg.", ".s....s.", ".s....s."], { "h": 0x55360f, "f": 0xe8c79a, "k": 0x202020, "w": 0xb05030, "g": 0x2f9a3a, "s": 0x6a4a22 }),
  "elder": bitmapFromRows(["..hhhh..", ".hffffh.", ".fkffkf.", ".fwwwwf.", ".wwwwww.", ".pppppp.", ".pp..pp.", ".pp..pp.", ".s....s.", ".s....s."], { "h": 0xcfcfcf, "f": 0xe8c79a, "k": 0x202020, "w": 0xe8e8e8, "p": 0x803060, "s": 0x6a4a22 }),
  "tree": bitmapFromRows(["..gggg..", ".gggggg.", "gggggggg", "gggggggg", ".gggggg.", "..gbbg..", "...bb...", "...bb..."], { "g": 0x2f8a3a, "b": 0x6a4a22 }),
  "house": bitmapFromRows(["....rrrrrrrr....", "...rrrrrrrrrr...", "..rrrrrrrrrrrr..", ".rrrrrrrrrrrrrr.", "wwwwwwwwwwwwwwww", "wYYwwwwwwwwYYwww", "wYYwwwwwwwwYYwww", "wwwwwwwddwwwwwww", "wwwwwwwddwwwwwww", "wwwwwwwddwwwwwww"], { "r": 0xa83232, "w": 0xcaa978, "Y": 0x70c0e0, "d": 0x5a3a18 }),
  "chest": bitmapFromRows(["........", ".YYYYYY.", ".YkkkkY.", ".YYYYYY.", ".YwwwwY.", ".YYYYYY.", "........", "........"], { "Y": 0xd8a23a, "k": 0x6a4a22, "w": 0xf0e0a0 }),
  "flower": bitmapFromRows(["........", "...r....", "..rYr...", "...r....", "...g....", "..ggg...", "........", "........"], { "r": 0xe05050, "Y": 0xf0e060, "g": 0x2f8a3a }),
  "grass": bitmapFromRows(["gggggggg", "gGgggGgg", "gggggggg", "ggGgggGg", "gggggggg", "gGgggggg", "gggggGgg", "gggggggg"], { "g": 0x4ca64c, "G": 0x3c8c3c }),
  "path": bitmapFromRows(["pppppppp", "pPpppppp", "pppppPpp", "pppppppp", "ppPppppp", "pppppppP", "pppppppp", "pPpppppp"], { "p": 0xc8b080, "P": 0xb09868 }),
  "water": bitmapFromRows(["wwwwwwww", "wWwwwWww", "wwwwwwww", "wwWwwwWw", "wwwwwwww", "wWwwwWww", "wwwwwwww", "wwWwwwWw"], { "w": 0x3060c0, "W": 0x5080e0 }),
  "floor": bitmapFromRows(["ffffffff", "fdfffdff", "ffffffff", "ffffffff", "fdfffdff", "ffffffff", "ffffffff", "fdfffdff"], { "f": 0x8a6a44, "d": 0x7a5a38 }),
  "bird": bitmapFromRows([".YYYY.", "YYYYkY", "YYYYYY", "rYYYY.", ".YYYY.", "..rr.."], { "Y": 0xf0c850, "k": 0x101010, "r": 0xe07020 }),
  "ship": bitmapFromRows(["...c...", "..ccc..", ".ccccc.", "cc.c.cc", "c.....c"], { "c": 0x60c8e0 }),
  "slime": bitmapFromRows(["..mm..", ".mmmm.", "mmkkmm", "mmmmmm", ".m.m.m"], { "m": 0x60c060, "k": 0x103010 }),
};
