// AUTO-GENERATED by bake/bake-gltf.ts from Khronos Fox (CC-BY-4.0).
// "Fox" by PixelMannen (CC0), rigged/animated by tomkranis (CC BY 4.0),
// glTF by @AsoboStudio + @scurest (CC BY 4.0). Attribution REQUIRED — see
// assets/vendor/CREDITS.md. Skinned: bone-batch partitioned for the PSP GE.
import { dcU8, dcI8, dcU16, dcF32 } from './dcpak';
import { PSM_8888 } from './g3d';
import type { BakedMesh } from './mesh';
import type { BakedTexture } from './assets-kenney-car';

export interface FoxBatch { jointTable: number[]; boneCount: number; mesh: BakedMesh }
export interface FoxClip { fps: number; frameCount: number; t: Float32Array; r: Float32Array; s: Float32Array }

export const FOX: {
  scale: number; jointCount: number; jointParents: Int8Array;
  inverseBindMatrices: Float32Array;
  bind: { t: Float32Array; r: Float32Array; s: Float32Array };
  boneLimit: number; batches: FoxBatch[]; texture: BakedTexture;
  clips: Record<string, FoxClip>;
} = {
  scale: 0.03, jointCount: 24, boneLimit: 4,
  jointParents: dcI8('fox:jointParents'),
  inverseBindMatrices: dcF32('fox:inverseBindMatrices'),
  bind: {
    t: dcF32('fox:bind.t'),
    r: dcF32('fox:bind.r'),
    s: dcF32('fox:bind.s'),
  },
  batches: [
    { jointTable: [2,13,16,20], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 96, weightCount: 4, triCount: 32,
    aabb: { min: [-11.53214,33.95345,-41.48656], max: [11.53214,64.69489,-16.6449] },
    vertices: dcU8('fox:batch.0.vertices'),
    indices: dcU16('fox:batch.0.indices'),
  } },
    { jointTable: [6,10,11,15], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 330, weightCount: 4, triCount: 110,
    aabb: { min: [-12.59272,13.99515,-88.095], max: [12.59272,78.90719,66.62486] },
    vertices: dcU8('fox:batch.1.vertices'),
    indices: dcU16('fox:batch.1.indices'),
  } },
    { jointTable: [2,3,16,17], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 117, weightCount: 4, triCount: 39,
    aabb: { min: [-9.99522,20.65462,-37.79313], max: [11.59716,65.034,-9.89555] },
    vertices: dcU8('fox:batch.2.vertices'),
    indices: dcU16('fox:batch.2.indices'),
  } },
    { jointTable: [7,8,14,15], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 156, weightCount: 4, triCount: 52,
    aabb: { min: [-10.43365,14.29642,-88.095], max: [8.62242,42.55341,27.42514] },
    vertices: dcU8('fox:batch.3.vertices'),
    indices: dcU16('fox:batch.3.indices'),
  } },
    { jointTable: [3,4,10,16], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 96, weightCount: 4, triCount: 32,
    aabb: { min: [-11.43497,29.36634,-10.71592], max: [11.43497,66.90525,27.42514] },
    vertices: dcU8('fox:batch.4.vertices'),
    indices: dcU16('fox:batch.4.indices'),
  } },
    { jointTable: [4,5,7,10], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 96, weightCount: 4, triCount: 32,
    aabb: { min: [-11.29993,29.36634,8.65362], max: [11.20747,71.51919,36.29143] },
    vertices: dcU8('fox:batch.5.vertices'),
    indices: dcU16('fox:batch.5.indices'),
  } },
    { jointTable: [2,3,20,21], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 81, weightCount: 4, triCount: 27,
    aabb: { min: [-11.59716,20.65462,-37.79313], max: [0,58.75623,-9.95905] },
    vertices: dcU8('fox:batch.6.vertices'),
    indices: dcU16('fox:batch.6.indices'),
  } },
    { jointTable: [3,4,7,20], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 18, weightCount: 4, triCount: 6,
    aabb: { min: [-11.29993,32.85219,-10.40698], max: [-5.0273,52.63343,11.31834] },
    vertices: dcU8('fox:batch.7.vertices'),
    indices: dcU16('fox:batch.7.indices'),
  } },
    { jointTable: [4,7,10,11], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 24, weightCount: 4, triCount: 8,
    aabb: { min: [0,27.98152,10.99233], max: [10.43365,37.51073,24.60131] },
    vertices: dcU8('fox:batch.8.vertices'),
    indices: dcU16('fox:batch.8.indices'),
  } },
    { jointTable: [4,7,8,10], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 24, weightCount: 4, triCount: 8,
    aabb: { min: [-10.43365,27.98152,10.99233], max: [0,37.51073,24.60131] },
    vertices: dcU8('fox:batch.9.vertices'),
    indices: dcU16('fox:batch.9.indices'),
  } },
    { jointTable: [3,4,7,10], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 12, weightCount: 4, triCount: 4,
    aabb: { min: [-5.43377,32.0535,-9.95905], max: [5.43379,34.24561,15.64268] },
    vertices: dcU8('fox:batch.10.vertices'),
    indices: dcU16('fox:batch.10.indices'),
  } },
    { jointTable: [4,5,6,0], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 66, weightCount: 4, triCount: 22,
    aabb: { min: [-10.69394,43.62217,32.14676], max: [10.69391,73.62648,43.21889] },
    vertices: dcU8('fox:batch.11.vertices'),
    indices: dcU16('fox:batch.11.indices'),
  } },
    { jointTable: [2,13,14,15], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 102, weightCount: 4, triCount: 34,
    aabb: { min: [-8.62242,20.1497,-68.047], max: [8.62242,56.2355,-40.80971] },
    vertices: dcU8('fox:batch.12.vertices'),
    indices: dcU16('fox:batch.12.indices'),
  } },
    { jointTable: [2,16,17,18], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 84, weightCount: 4, triCount: 28,
    aabb: { min: [2.05637,15.7987,-40.3275], max: [11.59716,35.21442,-16.70686] },
    vertices: dcU8('fox:batch.13.vertices'),
    indices: dcU16('fox:batch.13.indices'),
  } },
    { jointTable: [2,20,21,22], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 84, weightCount: 4, triCount: 28,
    aabb: { min: [-11.59716,15.7987,-40.3275], max: [-2.05637,35.21442,-16.70686] },
    vertices: dcU8('fox:batch.14.vertices'),
    indices: dcU16('fox:batch.14.indices'),
  } },
    { jointTable: [2,3,4,0], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 24, weightCount: 4, triCount: 8,
    aabb: { min: [-11.43497,50.8964,-11.35178], max: [11.43497,64.88542,8.0929] },
    vertices: dcU8('fox:batch.15.vertices'),
    indices: dcU16('fox:batch.15.indices'),
  } },
    { jointTable: [17,18,19,0], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 72, weightCount: 4, triCount: 24,
    aabb: { min: [4.47676,-0.12174,-40.3275], max: [9.36655,17.74519,-27.75013] },
    vertices: dcU8('fox:batch.16.vertices'),
    indices: dcU16('fox:batch.16.indices'),
  } },
    { jointTable: [8,9,11,12], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 174, weightCount: 4, triCount: 58,
    aabb: { min: [-9.03897,-0.05987,14.55], max: [9.03897,17.7092,25.20934] },
    vertices: dcU8('fox:batch.17.vertices'),
    indices: dcU16('fox:batch.17.indices'),
  } },
    { jointTable: [21,22,23,0], boneCount: 4, mesh: {
    format: 27, stride: 40, vertexCount: 72, weightCount: 4, triCount: 24,
    aabb: { min: [-9.36653,-0.12174,-40.3275], max: [-4.47676,17.74519,-27.75013] },
    vertices: dcU8('fox:batch.18.vertices'),
    indices: dcU16('fox:batch.18.indices'),
  } },
  ],
  clips: {
    Survey: { fps: 24, frameCount: 83,
      t: dcF32('fox:clip.0.t'),
      r: dcF32('fox:clip.0.r'),
      s: dcF32('fox:clip.0.s') },
    Walk: { fps: 24, frameCount: 18,
      t: dcF32('fox:clip.1.t'),
      r: dcF32('fox:clip.1.r'),
      s: dcF32('fox:clip.1.s') },
    Run: { fps: 24, frameCount: 29,
      t: dcF32('fox:clip.2.t'),
      r: dcF32('fox:clip.2.r'),
      s: dcF32('fox:clip.2.s') },
  },
  texture: {
    width: 128, height: 128, psm: PSM_8888,
    pixels: dcU8('fox:texture.pixels'),
  },
};
