// AUTO-GENERATED by bake/bake-gltf.ts from three.js Soldier.glb (MIT).
// Soldier.glb from the three.js examples model set, MIT licensed.
// The embedded JPEG diffuse texture was extracted and converted to PNG for
// DreamCart deterministic baking. See assets/vendor/CREDITS.md.
import { dcU8, dcI8, dcU16, dcF32 } from './dcpak';
import { PSM_8888 } from './g3d';
import type { BakedMesh } from './mesh';
import type { BakedTexture } from './assets-kenney-car';

export interface ThreeSoldierBatch { jointTable: number[]; boneCount: number; mesh: BakedMesh }
export interface ThreeSoldierClip { fps: number; frameCount: number; t: Float32Array; r: Float32Array; s: Float32Array }

export const THREE_SOLDIER: {
  scale: number; jointCount: number; jointParents: Int8Array;
  inverseBindMatrices: Float32Array;
  bind: { t: Float32Array; r: Float32Array; s: Float32Array };
  boneLimit: number; batches: ThreeSoldierBatch[]; texture: BakedTexture;
  clips: Record<string, ThreeSoldierClip>;
} = {
  scale: 0.012, jointCount: 49, boneLimit: 8,
  jointParents: dcI8('three-soldier:jointParents'),
  inverseBindMatrices: dcF32('three-soldier:inverseBindMatrices'),
  bind: {
    t: dcF32('three-soldier:bind.t'),
    r: dcF32('three-soldier:bind.r'),
    s: dcF32('three-soldier:bind.s'),
  },
  batches: [
    { jointTable: [0,1,2,41,42,43,44,45], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 2158, weightCount: 8, triCount: 3127,
    aabb: { min: [-24.53821,-18.2748,-0.0181], max: [24.3644,21.64159,130.81895] },
    vertices: dcU8('three-soldier:batch.0.vertices'),
    indices: dcU16('three-soldier:batch.0.indices'),
  } },
    { jointTable: [0,1,2,3,6,7,23,24], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 1143, weightCount: 8, triCount: 1514,
    aabb: { min: [-24.50521,-22.48187,123.62838], max: [30.08748,14.76041,168.27388] },
    vertices: dcU8('three-soldier:batch.1.vertices'),
    indices: dcU16('three-soldier:batch.1.indices'),
  } },
    { jointTable: [0,4,5,41,45,46,47,48], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 1748, weightCount: 8, triCount: 2817,
    aabb: { min: [-9.91492,-15.12067,-0.037], max: [20.02822,21.90441,183.18329] },
    vertices: dcU8('three-soldier:batch.2.vertices'),
    indices: dcU16('three-soldier:batch.2.indices'),
  } },
    { jointTable: [2,3,6,7,8,9,10,11], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 645, weightCount: 8, triCount: 966,
    aabb: { min: [-82.44627,-17.45834,134.56694], max: [-17.04053,5.72924,159.6395] },
    vertices: dcU8('three-soldier:batch.3.vertices'),
    indices: dcU16('three-soldier:batch.3.indices'),
  } },
    { jointTable: [9,12,13,15,16,18,21,22], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 268, weightCount: 8, triCount: 392,
    aabb: { min: [-87.31368,-12.79949,145.90399], max: [-73.90233,-0.83838,152.22801] },
    vertices: dcU8('three-soldier:batch.4.vertices'),
    indices: dcU16('three-soldier:batch.4.indices'),
  } },
    { jointTable: [9,15,16,17,18,19,20,21], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 216, weightCount: 8, triCount: 313,
    aabb: { min: [-92.20572,-10.64938,146.51888], max: [-78.70377,-4.4347,149.90961] },
    vertices: dcU8('three-soldier:batch.5.vertices'),
    indices: dcU16('three-soldier:batch.5.indices'),
  } },
    { jointTable: [9,12,13,14,18,19,21,22], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 95, weightCount: 8, triCount: 131,
    aabb: { min: [-92.38803,-10.45008,146.02776], max: [-78.62599,-1.41309,148.80412] },
    vertices: dcU8('three-soldier:batch.6.vertices'),
    indices: dcU16('three-soldier:batch.6.indices'),
  } },
    { jointTable: [9,10,11,12,13,15,18,40], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 58, weightCount: 8, triCount: 62,
    aabb: { min: [-82.52553,-12.28437,143.71994], max: [84.77144,-0.36624,150.07895] },
    vertices: dcU8('three-soldier:batch.7.vertices'),
    indices: dcU16('three-soldier:batch.7.indices'),
  } },
    { jointTable: [9,10,11,15,18,19,21,22], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 10, weightCount: 8, triCount: 8,
    aabb: { min: [-80.72387,-10.72088,144.72121], max: [-74.41382,-7.12974,146.82574] },
    vertices: dcU8('three-soldier:batch.8.vertices'),
    indices: dcU16('three-soldier:batch.8.indices'),
  } },
    { jointTable: [3,4,5,6,23,24,25,26], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 529, weightCount: 8, triCount: 742,
    aabb: { min: [-9.66367,-17.47471,138.21721], max: [77.86127,9.87958,164.77602] },
    vertices: dcU8('three-soldier:batch.9.vertices'),
    indices: dcU16('three-soldier:batch.9.indices'),
  } },
    { jointTable: [2,3,23,24,25,26,27,35], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 65, weightCount: 8, triCount: 45,
    aabb: { min: [19.51491,-14.60854,142.63428], max: [92.18736,2.65659,156.29395] },
    vertices: dcU8('three-soldier:batch.10.vertices'),
    indices: dcU16('three-soldier:batch.10.indices'),
  } },
    { jointTable: [26,27,28,29,36,37,39,40], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 302, weightCount: 8, triCount: 444,
    aabb: { min: [70.84019,-12.92152,139.58043], max: [84.77144,2.0184,152.22769] },
    vertices: dcU8('three-soldier:batch.11.vertices'),
    indices: dcU16('three-soldier:batch.11.indices'),
  } },
    { jointTable: [26,30,33,34,35,36,37,38], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 256, weightCount: 8, triCount: 373,
    aabb: { min: [76.56327,-10.15314,145.96124], max: [92.18736,-0.87907,152.22769] },
    vertices: dcU8('three-soldier:batch.12.vertices'),
    indices: dcU16('three-soldier:batch.12.indices'),
  } },
    { jointTable: [26,30,31,33,36,37,38,39], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 55, weightCount: 8, triCount: 61,
    aabb: { min: [77.99973,-10.50182,145.73735], max: [86.59592,-0.89142,149.95264] },
    vertices: dcU8('three-soldier:batch.13.vertices'),
    indices: dcU16('three-soldier:batch.13.indices'),
  } },
    { jointTable: [26,28,30,31,32,33,34,36], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 118, weightCount: 8, triCount: 159,
    aabb: { min: [78.96844,-7.33763,145.36998], max: [92.40655,-1.18688,148.86191] },
    vertices: dcU8('three-soldier:batch.14.vertices'),
    indices: dcU16('three-soldier:batch.14.indices'),
  } },
    { jointTable: [25,26,27,28,30,33,36,39], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 34, weightCount: 8, triCount: 24,
    aabb: { min: [69.51178,-9.2176,143.25511], max: [80.34531,-0.74096,149.31584] },
    vertices: dcU8('three-soldier:batch.15.vertices'),
    indices: dcU16('three-soldier:batch.15.indices'),
  } },
    { jointTable: [26,27,28,29,30,31,33,36], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 11, weightCount: 8, triCount: 8,
    aabb: { min: [75.5015,-5.83695,143.82294], max: [80.36192,-1.18688,146.63986] },
    vertices: dcU8('three-soldier:batch.16.vertices'),
    indices: dcU16('three-soldier:batch.16.indices'),
  } },
    { jointTable: [4,5,0,0,0,0,0,0], boneCount: 8, mesh: {
    format: 27, stride: 56, vertexCount: 109, weightCount: 8, triCount: 190,
    aabb: { min: [-5.79483,4.9533,161.53366], max: [5.78174,10.78426,173.77361] },
    vertices: dcU8('three-soldier:batch.17.vertices'),
    indices: dcU16('three-soldier:batch.17.indices'),
  } },
  ],
  clips: {
    Idle: { fps: 24, frameCount: 48,
      t: dcF32('three-soldier:clip.0.t'),
      r: dcF32('three-soldier:clip.0.r'),
      s: dcF32('three-soldier:clip.0.s') },
    Run: { fps: 24, frameCount: 18,
      t: dcF32('three-soldier:clip.1.t'),
      r: dcF32('three-soldier:clip.1.r'),
      s: dcF32('three-soldier:clip.1.s') },
    TPose: { fps: 24, frameCount: 2,
      t: dcF32('three-soldier:clip.2.t'),
      r: dcF32('three-soldier:clip.2.r'),
      s: dcF32('three-soldier:clip.2.s') },
    Walk: { fps: 24, frameCount: 26,
      t: dcF32('three-soldier:clip.3.t'),
      r: dcF32('three-soldier:clip.3.r'),
      s: dcF32('three-soldier:clip.3.s') },
  },
  texture: {
    width: 256, height: 256, psm: PSM_8888,
    pixels: dcU8('three-soldier:texture.pixels'),
  },
};
