// AUTO-GENERATED by bake/bake-gltf.ts from Kenney Nature Kit (CC0).
// Flat-colored low-poly props (color baked per-vertex; no texture).
import { dcU8, dcU16 } from './dcpak';
import type { BakedMesh } from './mesh';

export const NATURE_FORMAT = 7;
export const NATURE_STRIDE = 28;

export const NATURE_PROPS: Record<string, BakedMesh> = {
  tree: {
    format: 7, stride: 28, vertexCount: 240, weightCount: 0, triCount: 62,
    aabb: { min: [-0.17732,-0.05,-0.20475], max: [0.17732,1.46944,0.20475] },
    vertices: dcU8('nature:tree.vertices'),
    indices: dcU16('nature:tree.indices'),
  },
  rock: {
    format: 7, stride: 28, vertexCount: 60, weightCount: 0, triCount: 16,
    aabb: { min: [-0.1804,-0.05,-0.1804], max: [0.1804,0.14122,0.1804] },
    vertices: dcU8('nature:rock.vertices'),
    indices: dcU16('nature:rock.indices'),
  },
  bush: {
    format: 7, stride: 28, vertexCount: 48, weightCount: 0, triCount: 16,
    aabb: { min: [-0.19149,-0.05,-0.16817], max: [0.19149,0.15729,0.16817] },
    vertices: dcU8('nature:bush.vertices'),
    indices: dcU16('nature:bush.indices'),
  },
  grass: {
    format: 7, stride: 28, vertexCount: 84, weightCount: 0, triCount: 36,
    aabb: { min: [-0.12304,-0.05,-0.13343], max: [0.11145,0.0925,0.12388] },
    vertices: dcU8('nature:grass.vertices'),
    indices: dcU16('nature:grass.indices'),
  },
};
