// AUTO-GENERATED by bake/bake-gltf.ts from Kenney Car Kit (CC0).
// Textured low-poly sedan: body + one wheel mesh + the 4 wheel offsets.
import { dcU8, dcU16 } from './dcpak';
import { PSM_8888 } from './g3d';
import type { BakedMesh } from './mesh';

export interface BakedTexture { width: number; height: number; psm: number; pixels: Uint8Array }

export const KENNEY_CAR: {
  format: number; stride: number;
  body: BakedMesh; wheel: BakedMesh;
  wheelOffsets: [number, number, number][];
  texture: BakedTexture;
} = {
  format: 15, stride: 36,
  body: {
    format: 15, stride: 36, vertexCount: 1072, weightCount: 0, triCount: 704,
    aabb: { min: [-0.75,0.15,-1.3], max: [0.75,1.3,1.25] },
    vertices: dcU8('car:body.vertices'),
    indices: dcU16('car:body.indices'),
  },
  wheel: {
    format: 15, stride: 36, vertexCount: 480, weightCount: 0, triCount: 332,
    aabb: { min: [-0.2,-0.3,-0.3], max: [0.2,0.3,0.3] },
    vertices: dcU8('car:wheel.vertices'),
    indices: dcU16('car:wheel.indices'),
  },
  wheelOffsets: [[-0.3,0.3,0.66],[0.3,0.3,-0.66],[-0.3,0.3,-0.66],[0.3,0.3,0.66]],
  texture: {
    width: 256, height: 256, psm: PSM_8888,
    pixels: dcU8('car:texture.pixels'),
  },
};
