// AUTO-GENERATED by framework/bake/bake-bsp.ts — DO NOT EDIT.
// Imported from a GoldSrc BSP v30 map: CC0 z-fight / cull test scene
// Original CC0 BSP v30 fixture (DreamCart)
//
// 3 sub-meshes · 21744 verts · 7248 tris · 3 textures (minArea 0.1 m²).
// Format 15 (UV|COLOR|NORMAL|POS), stride 36. texId indexes textures[];
// per-vertex COLOR carries a baked directional/lightmap shade (the GE modulates the
// texture over it; the vertex-colour software oracle uses it directly).
// Binary blobs (geometry, textures, collision) live in the .dcpak pack (see
// docs/dcpak-format.md); dcU8/dcU16 pull them as typed arrays by key — no base64.
import { dcU8, dcU16 } from './dcpak';
import type { BakedMesh } from './mesh';

export interface BspMesh extends BakedMesh { texId: number; }
interface RawMesh { texId: number; vertexCount: number; triCount: number; aabb: { min: number[]; max: number[] }; vertices: Uint8Array; indices: Uint16Array; }

const FORMAT = 15;
const STRIDE = 36;
const RAW_MESHES: RawMesh[] = [
  { texId: 0, vertexCount: 18816, triCount: 6272,
    aabb: { min: [-6.502, 0, -6.502], max: [6.502, 8.128, 6.502] },
    vertices: dcU8('bsp-zfight:m0.vertices'),
    indices: dcU16('bsp-zfight:m0.indices') },
  { texId: 1, vertexCount: 2736, triCount: 912,
    aabb: { min: [-1.829, 0, -5.486], max: [2.642, 4.267, 1.016] },
    vertices: dcU8('bsp-zfight:m1.vertices'),
    indices: dcU16('bsp-zfight:m1.indices') },
  { texId: 2, vertexCount: 192, triCount: 64,
    aabb: { min: [1.27, 0.508, -1.448], max: [2.388, 3.302, -1.422] },
    vertices: dcU8('bsp-zfight:m2.vertices'),
    indices: dcU16('bsp-zfight:m2.indices') },
];

function decode(c: RawMesh): BspMesh {
  return { texId: c.texId, format: FORMAT, stride: STRIDE, vertexCount: c.vertexCount, weightCount: 0,
    vertices: c.vertices, indices: c.indices, triCount: c.triCount,
    aabb: { min: [c.aabb.min[0], c.aabb.min[1], c.aabb.min[2]], max: [c.aabb.max[0], c.aabb.max[1], c.aabb.max[2]] } };
}

export const BSP_ZFIGHT = {
  name: "CC0 z-fight / cull test scene",
  title: "BSP TEST - ZFIGHT",
  attribution: "Original CC0 BSP v30 fixture (DreamCart)",
  /** [x, z, heading] (XZ centred on the map) + floorY (engine-Y the player stands on). */
  spawn: [0, 5.08, 1.571] as [number, number, number],
  floorY: 0,
  spawnY: 1.219,
  span: 8.502,
  groundColor: 0x3a3d42,
  skyColor: 0x10141e,
  /** Wall collision rectangles [minX, minZ, maxX, maxZ] × N (XZ centred). */
  solidAABBs: dcU8('bsp-zfight:solidAABBs'),
  /** Floor-height spans [minX, minZ, maxX, maxZ, y] × N (XZ centred) for stand-on-floor tracking. */
  floorSpans: dcU8('bsp-zfight:floorSpans'),
  /** Per-miptex textures (PSM_8888, REPEAT); meshes index this by texId. */
  textures: [
  { width: 64, height: 64, psm: 3, pixels: dcU8('bsp-zfight:tex0') },
  { width: 64, height: 64, psm: 3, pixels: dcU8('bsp-zfight:tex1') },
  { width: 32, height: 32, psm: 3, pixels: dcU8('bsp-zfight:tex2') },
  ],
  meshes(): BspMesh[] { return RAW_MESHES.map(decode); },
};
