// Bakes bake/sprite-defs into src/assets-sprites.ts (bitmaps built via the
// framework's bitmapFromRows). Run: bun framework/bake/bake-sprites.ts
import { SPRITE_DEFS } from "./sprite-defs.ts";

const here = new URL(".", import.meta.url).pathname;
const outFile = here + "../src/assets-sprites.ts";

let out = "// AUTO-GENERATED by bake/bake-sprites.ts from bake/sprite-defs.ts.\n";
out += "import { Bitmap, bitmapFromRows } from './bitmap';\n\nexport const SPRITES: Record<string, Bitmap> = {\n";
for (const [name, def] of Object.entries(SPRITE_DEFS)) {
  const rows = def.rows.map((r) => JSON.stringify(r)).join(", ");
  const map = Object.entries(def.map)
    .map(([k, v]) => JSON.stringify(k) + ": 0x" + (v >>> 0).toString(16).padStart(6, "0"))
    .join(", ");
  out += "  " + JSON.stringify(name) + ": bitmapFromRows([" + rows + "], { " + map + " }),\n";
}
out += "};\n";
await Bun.write(outFile, out);
console.log("bake-sprites: wrote", Object.keys(SPRITE_DEFS).length, "sprites -> src/assets-sprites.ts");
