// Bakes a bitmap font into src/assets-font.ts from the vendored public-domain
// font8x8 (bake/font8x8_basic.h, dhepper/font8x8). bit0 = leftmost pixel, which
// matches our renderer. Run: bun framework/bake/bake-font.ts
import { existsSync } from "node:fs";

const here = new URL(".", import.meta.url).pathname;
const outFile = here + "../src/assets-font.ts";
const cacheFile = here + "font8x8_basic.h"; // vendored, public domain
const URL_SRC = "https://raw.githubusercontent.com/dhepper/font8x8/master/font8x8_basic.h";

let text: string;
if (existsSync(cacheFile)) {
  text = await Bun.file(cacheFile).text();
} else {
  try {
    const res = await fetch(URL_SRC);
    if (!res.ok) throw new Error("HTTP " + res.status);
    text = await res.text();
  } catch (e) {
    console.warn("bake-font: no cache and fetch failed (" + e + "); keeping fallback font.");
    process.exit(0);
  }
}

const groups: number[][] = [];
const re = /\{([^}]*)\}/g;
let m: RegExpExecArray | null;
while ((m = re.exec(text))) {
  const bytes = m[1].match(/0x[0-9a-fA-F]+/g);
  if (bytes && bytes.length === 8) groups.push(bytes.map((b) => parseInt(b, 16)));
}
if (groups.length < 128) {
  console.warn("bake-font: unexpected parse (" + groups.length + "); keeping fallback.");
  process.exit(0);
}

let out = "// AUTO-GENERATED by bake/bake-font.ts from dhepper/font8x8 (public domain).\n";
out += "import { Font, setFont } from './font';\n\nexport const FONT8X8: Font = {\n  height: 8,\n  glyphs: {\n";
let count = 0;
for (let code = 32; code <= 126; code++) {
  const rows = groups[code];
  let maxCol = -1;
  for (const r of rows) for (let c = 0; c < 8; c++) if (r & (1 << c)) maxCol = Math.max(maxCol, c);
  const w = maxCol < 0 ? 3 : maxCol + 1;
  out += "    " + code + ": { w: " + w + ", rows: [" + rows.join(",") + "] },\n";
  count++;
}
out += "  },\n  fallback: { w: 6, rows: [62,34,34,34,34,34,62,0] },\n};\n\nsetFont(FONT8X8);\n";
await Bun.write(outFile, out);
console.log("bake-font: wrote", count, "glyphs -> src/assets-font.ts");
