// Bakes CC0 VFX sprite SHEETS (assets/vendor/vfx/*.png) into RGBA texture frames
// (framework/src/assets-vfx.ts) for ADDITIVE billboard hit effects (rpgbattle3d.js).
// Each frame is box-downscaled and PREMULTIPLIED (rgb *= alpha) so the engine's
// additive blend (OP_SET_BLEND 1 -> blendFunc ONE,ONE) reproduces the soft glow that
// the no-blend cutout path could not. See assets/vendor/CREDITS.md.
//
// Run:  bun framework/bake/bake-vfx.ts        (part of `bun run bake`)
import UPNG from 'upng-js';
import { readFileSync, writeFileSync, existsSync } from 'fs';

const ROOT = new URL('../../', import.meta.url).pathname;
const vendor = ROOT + 'assets/vendor/vfx/';

interface VfxConf { file: string; cols: number; rows: number; first: number; frames: number; size: number; }
const VFX: Record<string, VfxConf> = {
  // StumpyStrust "Explosion Sheet" boom3 (CC0) — fiery burst; the bright opening frames.
  BOOM: { file: 'boom3.png', cols: 8, rows: 8, first: 0, frames: 22, size: 64 },
  // kurohina "Spark effect" (CC0) — bright star-burst hit spark.
  SPARK: { file: 'spark_strip9.png', cols: 9, rows: 1, first: 0, frames: 9, size: 32 },
};

/** Box-downscale RGBA region (sx,sy,fw,fh) of `src` (W wide) to dw×dh, premultiplied. */
function downPremul(src: Uint8Array, W: number, sx: number, sy: number, fw: number, fh: number, dw: number, dh: number): Uint8Array {
  const out = new Uint8Array(dw * dh * 4);
  for (let y = 0; y < dh; y++) {
    const y0 = sy + Math.floor((y * fh) / dh), y1 = Math.max(y0 + 1, sy + Math.floor(((y + 1) * fh) / dh));
    for (let x = 0; x < dw; x++) {
      const x0 = sx + Math.floor((x * fw) / dw), x1 = Math.max(x0 + 1, sx + Math.floor(((x + 1) * fw) / dw));
      let r = 0, g = 0, b = 0, a = 0, n = 0;
      for (let yy = y0; yy < y1; yy++) for (let xx = x0; xx < x1; xx++) { const o = (yy * W + xx) * 4; r += src[o]; g += src[o + 1]; b += src[o + 2]; a += src[o + 3]; n++; }
      const av = a / n / 255, d = (y * dw + x) * 4;
      out[d] = ((r / n) * av) | 0; out[d + 1] = ((g / n) * av) | 0; out[d + 2] = ((b / n) * av) | 0; out[d + 3] = (a / n) | 0;
    }
  }
  return out;
}
const b64 = (u8: Uint8Array): string => Buffer.from(u8).toString('base64');

let out = `// AUTO-GENERATED by framework/bake/bake-vfx.ts — DO NOT EDIT.\n`;
out += `// Additive VFX frames (premultiplied RGBA) baked from CC0 sprite sheets\n`;
out += `// (assets/vendor/vfx/). See assets/vendor/CREDITS.md. Drawn as additive billboards.\n`;
out += `import { unb64 } from './b64';\n\n`;
out += `export interface VfxAnim { w: number; h: number; frames: Uint8Array[]; }\n`;
out += `function dec(s: string): Uint8Array { return unb64(s); }\n`;

for (const [name, c] of Object.entries(VFX)) {
  if (!existsSync(vendor + c.file)) { console.error(`[vfx] missing ${c.file} — fetch the CC0 sheet first`); process.exit(1); }
  const d = UPNG.decode(readFileSync(vendor + c.file));
  const rgba = new Uint8Array(UPNG.toRGBA8(d)[0]);
  const W = d.width, fw = (W / c.cols) | 0, fh = (d.height / c.rows) | 0, S = c.size;
  const lits: string[] = [];
  for (let i = 0; i < c.frames; i++) {
    const f = c.first + i, fx = (f % c.cols) * fw, fy = ((f / c.cols) | 0) * fh;
    lits.push(`  dec('${b64(downPremul(rgba, W, fx, fy, fw, fh, S, S))}'),`);
  }
  out += `\n/** ${name}: ${c.frames} frames @ ${S}px premultiplied RGBA (from ${c.file}). */\n`;
  out += `export const VFX_${name}: VfxAnim = { w: ${S}, h: ${S}, frames: [\n${lits.join('\n')}\n] };\n`;
  console.log(`[vfx] ${name}: ${c.frames} frames ${S}x${S} (premultiplied)`);
}

writeFileSync(ROOT + 'framework/src/assets-vfx.ts', out);
console.log(`wrote framework/src/assets-vfx.ts (${(out.length / 1024).toFixed(1)} KB)`);
