/**
 * ChangelogPage — the changelog shell: a dated-entry jump list + the
 * build-rendered markdown HTML body.
 *
 * CONTENT AGENT: do NOT edit this file to add entries — edit
 * web/content/changelog.md. Edit this only to restyle the changelog shell.
 */
import { Layout } from "../components";
import type { DocHeading } from "./DocsPage";

export interface ChangelogPageData {
  bodyHtml: string;
  /** h2 dated-entry headings for the jump list. */
  entries: DocHeading[];
}

export function ChangelogPage({ data }: { data: ChangelogPageData }) {
  return (
    <Layout active="changelog">
      <div className="docs-shell container">
        <aside className="docs-sidebar" aria-label="Versions">
          <p className="docs-sb-title">Versions</p>
          <ul>
            {data.entries.map((e) => (
              <li key={e.slug}>
                <a href={`#${e.slug}`}>{e.text}</a>
              </li>
            ))}
          </ul>
        </aside>
        <article
          className="docs-article"
          dangerouslySetInnerHTML={{ __html: data.bodyHtml }}
        />
      </div>
    </Layout>
  );
}
