/**
 * DocsPage — the docs shell: sidebar (DOCS_NAV) + the build-rendered markdown HTML
 * body + an on-this-page TOC. The build renders ONE static HTML file per slug; each
 * gets its own page-content module (generated) and passes it here.
 *
 * CONTENT AGENTS: do NOT edit this file to add prose — edit the markdown in
 * web/content/docs/<slug>.md. Edit this only to restyle the docs shell.
 */
import { Layout } from "../components";

export interface DocHeading {
  depth: number;
  text: string;
  slug: string;
}
export interface DocsPageData {
  /** Current slug ("" => Overview). */
  slug: string;
  title: string;
  /** Rendered markdown HTML for the body. */
  bodyHtml: string;
  /** Sidebar sections (from web/content/docs-nav.ts). */
  nav: { title: string; pages: { slug: string; title: string }[] }[];
  /** h2/h3 headings for the on-this-page TOC. */
  headings: DocHeading[];
}

function href(slug: string): string {
  return slug === "" ? "/docs/" : `/docs/${slug}/`;
}

export function DocsPage({ data }: { data: DocsPageData }) {
  return (
    <Layout active="docs">
      <div className="docs-shell container">
        <aside className="docs-sidebar" aria-label="Docs">
          {data.nav.map((section) => (
            <div className="docs-sb-section" key={section.title}>
              <p className="docs-sb-title">{section.title}</p>
              <ul>
                {section.pages.map((p) => (
                  <li key={p.slug}>
                    <a
                      href={href(p.slug)}
                      aria-current={p.slug === data.slug ? "page" : undefined}
                    >
                      {p.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </aside>

        <article
          className="docs-article"
          dangerouslySetInnerHTML={{ __html: data.bodyHtml }}
        />

        {data.headings.length > 0 && (
          <aside className="docs-toc" aria-label="On this page">
            <p className="docs-sb-title">On this page</p>
            <ul>
              {data.headings.map((h) => (
                <li key={h.slug} data-depth={h.depth}>
                  <a href={`#${h.slug}`}>{h.text}</a>
                </li>
              ))}
            </ul>
          </aside>
        )}
      </div>
    </Layout>
  );
}
