// Builds web/games.generated.js — the manifest the Playground loads.
//  - raw low-level demos (runtime/src/game/raw-<name>.js): editable + run.
//  - framework games (framework/games/<name>.js, bundled by `bun framework/build.ts`):
//    the playground shows the authored JS source and runs the prebuilt bundle.
// Run: bun web/build-games.ts   (run the framework build first for framework games)
import { readdirSync, existsSync } from "node:fs";

const here = new URL(".", import.meta.url).pathname;
const runDir = here + "../runtime/src/game/";
const fwDir = here + "../framework/games/";

// Each game's metadata (title / menu order / controls) is declared in the game's
// own source as a header comment — the single source of truth — so adding a game
// needs no edit here:
//   // @title Snake
//   // @order 5
//   // @controls D-pad to steer
// Anything missing falls back to the file name / order 99 / no controls.
function parseMeta(src: string): { title?: string; order?: number; controls?: string } {
  const tag = (name: string) => src.match(new RegExp(`^//\\s*@${name}\\s+(.+)$`, "m"))?.[1].trim();
  const order = tag("order");
  return { title: tag("title"), order: order === undefined ? undefined : parseInt(order, 10), controls: tag("controls") };
}

export async function buildGames(): Promise<number> {
  const files = readdirSync(runDir).filter((f) => f.endsWith(".js")).sort();
  const games: Record<string, unknown> = {};
  for (const f of files) {
    const name = f.replace(/\.js$/, "");
    const srcPath = fwDir + name + ".js"; // authored framework source (JS)
    const isFw = existsSync(srcPath);
    // framework games run the prebuilt bundle but display the authored source;
    // raw games are self-contained, so source == what runs.
    const src = isFw ? await Bun.file(srcPath).text() : await Bun.file(runDir + f).text();
    const meta = parseMeta(src);
    // Per-game binary asset pack (docs/dcpak-format.md), embedded base64 so the
    // playground needs no extra fetch; engine.js decodes it to __dcpak before eval.
    // Empty (32-byte header) and missing packs are omitted to keep the manifest
    // small — asset-free games read nothing.
    const pakPath = runDir + name + ".dcpak";
    let dcpak = "";
    if (existsSync(pakPath)) {
      const bytes = new Uint8Array(await Bun.file(pakPath).arrayBuffer());
      if (bytes.length > 32) dcpak = Buffer.from(bytes).toString("base64");
    }
    games[f] = {
      title: meta.title ?? name,
      order: meta.order ?? 99,
      controls: meta.controls ?? "",
      kind: isFw ? "fw" : "raw",
      run: await Bun.file(runDir + f).text(),
      src,
      lang: "js", // everything authored in JS now
      dcpak, // base64 .dcpak ("" when the game has no baked assets)
    };
  }
  await Bun.write(
    here + "games.generated.js",
    "// AUTO-GENERATED by web/build-games.ts — do not edit.\nwindow.GAMES = " + JSON.stringify(games, null, 2) + ";\n",
  );
  return Object.keys(games).length;
}

if (import.meta.main) {
  const n = await buildGames();
  console.log("wrote web/games.generated.js with", n, "games");
}
