// Builds web/games.generated.js — the manifest the Playground loads.
//  - raw low-level demos (runtime/src/game/raw-<name>.js): editable + run.
//  - framework games (framework/games/<name>.js, bundled by `bun framework/build.ts`):
//    the playground shows the authored JS source and runs the prebuilt bundle.
// Run: bun web/build-games.ts   (run the framework build first for framework games)
import { readdirSync, existsSync } from "node:fs";

const here = new URL(".", import.meta.url).pathname;
const runDir = here + "../runtime/src/game/";
const fwDir = here + "../framework/games/";

// Framework games (built bundle name == authored source name, no prefix) come
// first; the raw- prefixed low-level demos follow. Anything without an entry
// falls back to its file name and order 99.
const META: Record<string, { title: string; order: number }> = {
  "rpg.js": { title: "Wuxia Village", order: 0 },
  "maze.js": { title: "Maze", order: 1 },
  "shooter.js": { title: "Shooter", order: 2 },
  "flappy.js": { title: "Flappy", order: 3 },
  "dodge.js": { title: "Dodge", order: 4 },
  "snake.js": { title: "Snake", order: 5 },
  "raw-snake.js": { title: "Snake (raw API)", order: 10 },
  "raw-pong.js": { title: "Pong (raw API)", order: 11 },
  "raw-g2048.js": { title: "2048 (raw API)", order: 12 },
  "raw-breakout.js": { title: "Breakout (raw API)", order: 13 },
  "raw-tetris.js": { title: "Tetris (raw API)", order: 14 },
  "raw-platformer.js": { title: "Platformer (raw API)", order: 15 },
};

export async function buildGames(): Promise<number> {
  const files = readdirSync(runDir).filter((f) => f.endsWith(".js")).sort();
  const games: Record<string, unknown> = {};
  for (const f of files) {
    const name = f.replace(/\.js$/, "");
    const srcPath = fwDir + name + ".js"; // authored framework source (JS)
    const isFw = existsSync(srcPath);
    games[f] = {
      title: META[f]?.title ?? name,
      order: META[f]?.order ?? 99,
      kind: isFw ? "fw" : "raw",
      // framework games run the prebuilt bundle but display the authored source;
      // raw games are self-contained, so source == what runs.
      run: await Bun.file(runDir + f).text(),
      src: isFw ? await Bun.file(srcPath).text() : await Bun.file(runDir + f).text(),
      lang: "js", // everything authored in JS now
    };
  }
  await Bun.write(
    here + "games.generated.js",
    "// AUTO-GENERATED by web/build-games.ts — do not edit.\nwindow.GAMES = " + JSON.stringify(games, null, 2) + ";\n",
  );
  return Object.keys(games).length;
}

if (import.meta.main) {
  const n = await buildGames();
  console.log("wrote web/games.generated.js with", n, "games");
}
