// Builds web/games.generated.js — the manifest the Playground loads.
//  - raw JS games (runtime/src/game/<name>.js): editable + run.
//  - framework games (framework/games/<name>.ts, bundled by `bun framework/build.ts`):
//    the playground shows the TS source and runs the prebuilt bundle.
// Run: bun web/build-games.ts   (run the framework build first for fw games)
import { readdirSync, existsSync } from "node:fs";

const here = new URL(".", import.meta.url).pathname;
const runDir = here + "../runtime/src/game/";
const fwDir = here + "../framework/games/";

const META: Record<string, { title: string; order: number }> = {
  "snake.js": { title: "Snake", order: 0 },
  "pong.js": { title: "Pong", order: 1 },
  "g2048.js": { title: "2048", order: 2 },
  "breakout.js": { title: "Breakout", order: 3 },
  "tetris.js": { title: "Tetris", order: 4 },
  "platformer.js": { title: "Platformer", order: 5 },
  "fw-rpg.js": { title: "Wuxia Village (framework)", order: 10 },
  "fw-maze.js": { title: "Maze (framework)", order: 11 },
  "fw-shooter.js": { title: "Shooter (framework)", order: 12 },
  "fw-flappy.js": { title: "Flappy (framework)", order: 13 },
  "fw-dodge.js": { title: "Dodge (framework)", order: 14 },
  "fw-snake.js": { title: "Snake (framework)", order: 15 },
};

export async function buildGames(): Promise<number> {
  const files = readdirSync(runDir).filter((f) => f.endsWith(".js")).sort();
  const games: Record<string, unknown> = {};
  for (const f of files) {
    const name = f.replace(/\.js$/, "");
    const tsPath = fwDir + name + ".ts";
    const isFw = existsSync(tsPath);
    games[f] = {
      title: META[f]?.title ?? name,
      order: META[f]?.order ?? 99,
      kind: isFw ? "fw" : "raw",
      run: await Bun.file(runDir + f).text(),
      src: isFw ? await Bun.file(tsPath).text() : await Bun.file(runDir + f).text(),
      lang: isFw ? "ts" : "js",
    };
  }
  await Bun.write(
    here + "games.generated.js",
    "// AUTO-GENERATED by web/build-games.ts — do not edit.\nwindow.GAMES = " + JSON.stringify(games, null, 2) + ";\n",
  );
  return Object.keys(games).length;
}

if (import.meta.main) {
  const n = await buildGames();
  console.log("wrote web/games.generated.js with", n, "games");
}
